name: tokyo_flutter_hackathon
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  url_strategy: ^0.2.0
  responsive_builder: ^0.7.0
  provider: ^6.0.2
  go_router: ^10.0.0
  url_launcher: ^6.0.20
  flutter_html: ^3.0.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - resources/
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: resources/fonts/NotoSansJP-Regular.otf
        - asset: resources/fonts/NotoSansJP-Bold.otf
          weight: 700
    - family: YesevaOne
      fonts:
        - asset: resources/fonts/YesevaOne-Regular.ttf
    - family: ZenAntiqueSoft
      fonts:
        - asset: resources/fonts/ZenAntiqueSoft-Regular.ttf
    - family: NotoColorEmoji
      fonts:
        - asset: resources/fonts/NotoColorEmoji-Regular.ttf
